<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Attribute\Module'                        => __DIR__ . '/Module.php',
    'Attribute\Controller\AttributeController' => __DIR__ . '/src/Attribute/Controller/AttributeController.php',
    'AttributeTest\Framework\TestCase'        => __DIR__ . '/tests/Attribute/Framework/TestCase.php',
    'AttributeTest\SampleTest'                => __DIR__ . '/tests/Attribute/SampleTest.php',
);
