<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MonHoc\Module'                        => __DIR__ . '/Module.php',
    'MonHoc\Controller\MonHocController' => __DIR__ . '/src/MonHoc/Controller/MonHocController.php',
    'MonHocTest\Framework\TestCase'        => __DIR__ . '/tests/MonHoc/Framework/TestCase.php',
    'MonHocTest\SampleTest'                => __DIR__ . '/tests/MonHoc/SampleTest.php',
);
