<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'NgoaiNgu\Module'                        => __DIR__ . '/Module.php',
    'NgoaiNgu\Controller\NgoaiNguController' => __DIR__ . '/src/NgoaiNgu/Controller/NgoaiNguController.php',
    'NgoaiNguTest\Framework\TestCase'        => __DIR__ . '/tests/NgoaiNgu/Framework/TestCase.php',
    'NgoaiNguTest\SampleTest'                => __DIR__ . '/tests/NgoaiNgu/SampleTest.php',
);
