<!-- Nếu tồn tại có chọn 1 giảng viên nào nó thì mới hiển thị thông tin -->
<!-- nếu tồn tại id và đã đăng nhập và user_id đang đăng nhập bằng vs id -->
<!-- id=user_id thì sẽ hiển thị nút sửa -->
<!-- hoặc nếu user đăng nhập có quyền sửa tất cả thông tin của tất cả user thì sẻ button edit sẽ chuyển tới action edit luôn -->
<?php $id=$this->id; ?>
<?php $can_edit=$this->can_edit; ?>
<?php if($id){ ?>
  <?php 
    if($can_edit==1){
      // biến sử dụng chung
      $all_attributes=$this->all_attributes;
      $certificate_lists=$this->certificate_lists;
      $teaching_alls=$this->teaching_alls;
      $future_teaching_alls=$this->future_teaching_alls;
      $bac_hocs=$this->bac_hoc;
      $he_dao_taos=$this->he_dao_tao;
      $science_activity_alls=$this->science_activity_alls;
      $science_researchs=$this->science_researchs;
    }
  ?>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h3 class="header-thong-tin-ca-nhan">A. Thông tin cá nhân</h3>
      </div> 
    </div> 

    <div class="row">
      <div class="col-xs-9 col-sm-10 col-md-10 col-lg-10">
        <h3><small><b>1. Thông tin cá nhân</b></small></h3>
      </div>
      <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 text-right">
        <?php if($can_edit==1){ ?>
          <a class="btn btn-default" data-toggle="modal" data-target="#modal-infor-1"><b class="glyphicon glyphicon-pencil"></b></a>
        <?php } ?>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <td class="active">Tiêu đề</td>
            <td class="active">Nội dung</td>                    
          </tr>
        </thead>
        <tbody> 
          <?php 
            // thông tin giảng viên
            $infor_jos_infors=$this->infor_jos_infors;
            $ngoai_ngu=$this->ngoai_ngu; 
            // thông tin option
            $infor_array_options=$this->infor_array_options;
          ?>
          <?php foreach ($infor_jos_infors as $key => $infor_jos_infor) { ?> 
            <?php 
              // nếu không có value thì không cần kiểm tra frontend_input có phải là kiểu select không
              if(!isset($infor_jos_infor['value'])){ 
                $infor_jos_infor['frontend_input']=='Text';
                $infor_jos_infor['value']='';
              }
              // nếu kiểu select thì lấy tên hiển thị của option của select
              if($infor_jos_infor['frontend_input']=='Select' and $infor_jos_infor['value']){ 
                $infor_jos_infor['value']=$infor_array_options[$infor_jos_infor['attribute_code']][$infor_jos_infor['value']];                    
              } 
            ?>   
            <tr>
              <td><?php echo $infor_jos_infor['frontend_label'] ?></td>
              <td><?php echo $infor_jos_infor['value'] ?></td>
            </tr> 
          <?php } ?>             
                           
        </tbody>
      </table>
    </div>
    
    <div class="row">
      <div class="col-xs-9 col-sm-10 col-md-10 col-lg-10">
        <h3><small>2. Các chứng chỉ</small></h3>
      </div>
      <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 text-right">
        <?php if($can_edit==1){ ?>
          <a class="btn btn-default" data-toggle="modal" data-target="#modal-infor-2"><b class="glyphicon glyphicon-pencil"></b></a>
        <?php } ?>
      </div>
    </div>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Nội dung</td>
            <td class="active">Trạng thái</td>
            <td class="active">Ghi chú</td>                   
          </tr>
        </thead>
        <tbody> 
          <?php 
            $certificate_infors=$this->certificate_infors; 
            foreach ($certificate_infors as $key => $certificate_infor) {
          ?>
            <?php if($certificate_infor['name']!='Ngoại ngữ'){ ?>
              <tr>
                <td data-title="STT"><?php $key++; echo $key; ?></td>
                <td data-title="Nội dung"><?php echo $certificate_infor['name']; ?></td>
                <td data-title="Trạng thái">
                  <?php
                    $trang_thai='Không';
                    $note='';
                    if(isset($certificate_infor['note']) and $certificate_infor['note']!='0'){
                      $trang_thai='Có';
                      $note=$certificate_infor['note'];
                    }
                    echo $trang_thai;
                  ?>
                </td>                   
                <td data-title="Ghi chú"><?php echo $note; ?></td> 
              </tr>
            <?php }else{ ?>
              <tr>
                <td data-title="STT"><?php $key++; echo $key; ?></td>
                <td data-title="Nội dung"><?php echo $certificate_infor['name']; ?></td>
                <td data-title="Loại ngoại ngữ">
                  <?php
                    if(isset($certificate_infor['note']) and $certificate_infor['note']!='0' and isset($ngoai_ngu[$certificate_infor['note']])){
                      echo $ngoai_ngu[$certificate_infor['note']];
                    }
                  ?>
                </td>                   
                <td data-title="Trình độ">
                  <?php 
                    if(isset($certificate_infor['level'])){
                      echo $certificate_infor['level'];
                    }
                  ?>
                </td> 
              </tr>
            <?php } ?>
          <?php
            }
          ?> 
        </tbody>
      </table>
    </div>

    <h3>B. Kinh nghiệm làm việc</h3>    
    <div class="row">
      <div class="col-xs-9 col-sm-10 col-md-10 col-lg-10">
        <h3><small>1. Công tác giảng dạy</small></h3>
      </div>
      <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 text-right">
        <?php if($can_edit==1){ ?>
          <a class="btn btn-default" data-toggle="modal" data-target="#modal-cong-tac-giang-day-add"><b class="glyphicon glyphicon-plus"></b></a>
        <?php } ?>
      </div>
    </div>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">                  
          <tr>
            <td class="active">STT</td>
            <td class="active">Tên môn</td>
            <td class="active">Số tiết</td> 
            <td class="active">Bậc học</td>
            <td class="active">Hệ đào tạo</td>
            <td class="active">Ghi chú</td> 
            <?php if($can_edit==1){ ?>
              <td class="active td-remove">Xóa</td>
              <td class="active td-edit">Sửa</td>
            <?php } ?>                 
          </tr>
        </thead>
        <tbody>
        <?php foreach ($teaching_alls as $key => $teaching) { ?>                  
          <tr>
            <td data-title="STT"><span class="hidden-xs hidden-sm hidden-md hidden-lg"><?php echo $teaching['value_id']; ?></span><?php $key++; echo $key; ?></td>
            <td data-title="Tên môn"><span class="hidden-xs hidden-sm hidden-md hidden-lg"><?php echo $teaching['subject_id']; ?></span><?php echo $teaching['name']; ?></td>
            <td data-title="Số tiết"><?php echo $teaching['lesson_number']; ?></td> 
            <td data-title="Bậc học"><?php echo $teaching['qualifications']; ?></td>
            <td data-title="Hệ đào tạo"><?php echo $teaching['edu_system']; ?></td>
            <td data-title="Ghi chú"><?php echo $teaching['note']; ?></td>   
            <?php if($can_edit==1){ ?>
              <td data-title="Xóa">
                <a class="btn btn-default" onclick="deleteConfirm('Bạn muốn xóa công tác giảng dạy?', '<?php echo $this->url('application/crud', array('action'=>'delete-teaching', 'id'=>$teaching['value_id'])); ?>')"><b class="glyphicon glyphicon-remove"></b></a>
              </td>
              <td data-title="Sửa">
                <a class="btn btn-default ctgd-btn-edit" data-toggle="modal" data-target="#modal-cong-tac-giang-day-edit"><b class="glyphicon glyphicon-pencil"></b></a>
              </td>
            <?php } ?>                  
          </tr>
          <?php } ?>         
        </tbody>
      </table>
    </div>
















    <h3><small>2. Công tác nghiên cứu khoa học</small></h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Tham gia hoạt động</td>
            <td class="active">Trạng thái</td> 
            <td class="active">Thời gian bắt đầu</td>
            <td class="active">Thời gian kết thúc</td>
            <td class="active">Ghi chú</td>                 
          </tr>
        </thead>
        <tbody>  
          <?php foreach ($science_activity_alls as $key => $science_activity_all) { ?> 
            <?php 
              $activity_id=$science_activity_all['value_id'];
              $activity_name=$science_activity_all['name'];
              $trang_thai='Không';
              $time_from='';
              $time_to='';
              $note='';
              if(isset($science_researchs[$activity_id])){
                $trang_thai='Có';
                $time_from=$science_researchs[$activity_id]['time_from'];
                $time_to=$science_researchs[$activity_id]['time_to'];
                $note=$science_researchs[$activity_id]['note'];
              }
            ?>             
            <tr>
              <td data-title="STT"><?php $key++; echo $key; ?></td>
              <td data-title="Tham gia hoạt động"><?php echo  $activity_name; ?></td>              
              <td data-title="Trạng thái"><?php echo $trang_thai; ?></td> 
              <td data-title="Thời gian bắt đầu"><?php echo $time_from;?></td>
              <td data-title="Thời gian kết thúc"><?php echo $time_to;?></td>
              <td data-title="Ghi chú"><?php echo $note;?></td>
            </tr>
          <?php } ?>
          
        </tbody>
      </table>
    </div>














    <h3><small>3. Công tác khác</small></h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Nội dung</td>
            <td class="active">Thời gian</td> 
            <td class="active">Ghi chú</td>                
          </tr>
        </thead>
        <tbody>                  
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian">Nội dung</td> 
            <td data-title="Ghi chú">Ghi chú</td>                
          </tr>
          <tr>
            <td data-title="STT">2</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian">Nội dung</td> 
            <td data-title="Ghi chú">Ghi chú</td>                
          </tr>
        </tbody>
      </table>
    </div>













    <h3>C. Định hướng phát triển</h3>        
    <div class="row">
      <div class="col-xs-9 col-sm-10 col-md-10 col-lg-10">
        <h3><small>1. Công tác giảng dạy</small></h3>
      </div>
      <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 text-right">
        <?php if($can_edit==1){ ?>
          <a class="btn btn-default" data-toggle="modal" data-target="#modal-future-cong-tac-giang-day-add"><b class="glyphicon glyphicon-plus"></b></a>
        <?php } ?>
      </div>
    </div>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">                  
          <tr>
            <td class="active">STT</td>
            <td class="active">Tên môn</td>
            <td class="active">Số tiết</td> 
            <td class="active">Bậc học</td>
            <td class="active">Hệ đào tạo</td>
            <td class="active">Ghi chú</td> 
            <?php if($can_edit==1){ ?>
              <td class="active td-remove">Xóa</td>
              <td class="active td-edit">Sửa</td>
            <?php } ?>                 
          </tr>
        </thead>
        <tbody>
        <?php foreach ($future_teaching_alls as $key => $future_teaching) { ?>                  
          <tr>
            <td data-title="STT"><span class="hidden-xs hidden-sm hidden-md hidden-lg"><?php echo $future_teaching['value_id']; ?></span><?php $key++; echo $key; ?></td>
            <td data-title="Tên môn"><span class="hidden-xs hidden-sm hidden-md hidden-lg"><?php echo $future_teaching['subject_id']; ?></span><?php echo $future_teaching['name']; ?></td>
            <td data-title="Số tiết"><?php echo $future_teaching['lesson_number']; ?></td> 
            <td data-title="Bậc học"><?php echo $future_teaching['qualifications']; ?></td>
            <td data-title="Hệ đào tạo"><?php echo $future_teaching['edu_system']; ?></td>
            <td data-title="Ghi chú"><?php echo $future_teaching['note']; ?></td>   
            <?php if($can_edit==1){ ?>
              <td data-title="Xóa">
                <a class="btn btn-default" onclick="deleteConfirm('Bạn thật sự muốn xóa công tác giảng dạy?', '<?php echo $this->url('application/crud', array('action'=>'delete-future-teaching', 'id'=>$future_teaching['value_id'])); ?>')"><b class="glyphicon glyphicon-remove"></b></a>
              </td>
              <td data-title="Sửa">
                <a class="btn btn-default future-ctgd-btn-edit" data-toggle="modal" data-target="#modal-future-cong-tac-giang-day-edit"><b class="glyphicon glyphicon-pencil"></b></a>
              </td>
            <?php } ?>                  
          </tr>
          <?php } ?>         
        </tbody>
      </table>
    </div>



















    <h3><small>2. Công tác nghiên cứu khoa học</small></h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Nội dung</td>
            <td class="active">Thời gian bắt đầu</td> 
            <td class="active">Ghi chú</td>                 
          </tr>
        </thead>
        <tbody>                  
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td> 
            <td data-title="Ghi chú">Ghi chú</td>                 
          </tr>
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td> 
            <td data-title="Ghi chú">Ghi chú</td>                 
          </tr>
        </tbody>
      </table>
    </div>

    <h3><small>3. Học tập nâng cao trình độ</small></h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Nội dung</td>
            <td class="active">Nơi học</td> 
            <td class="active">Thời gian bắt đầu</td>
            <td class="active">Thời gian kết thúc</td>
            <td class="active">Ghi chú</td>                  
          </tr>
        </thead>
        <tbody>                  
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Nơi học">Nơi học</td> 
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td>
            <td data-title="Thời gian kết thúc">Thời gian kết thúc</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
          <tr>
            <td data-title="STT">2</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Nơi học">Nơi học</td> 
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td>
            <td data-title="Thời gian kết thúc">Thời gian kết thúc</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
        </tbody>
      </table>
    </div>

    <h3><small>4. Các hoạch định khác</small></h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Nội dung</td>
            <td class="active">Thời gian bắt đầu</td> 
            <td class="active">Thời gian kết thúc</td>
            <td class="active">Ghi chú</td>                  
          </tr>
        </thead>
        <tbody>                  
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td> 
            <td data-title="Thời gian kết thúc">Thời gian kết thúc</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Nội dung">Nội dung</td>
            <td data-title="Thời gian bắt đầu">Thời gian bắt đầu</td> 
            <td data-title="Thời gian kết thúc">Thời gian kết thúc</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
        </tbody>
      </table>
    </div>

    <h3>D. Các bài báo cáo khoa học đã công bố</h3>
    <div class="table-responsive" id="no-more-tables">
      <table class="table table-bordered table-hover cf">
        <thead class="cf">
          <tr>
            <td class="active">STT</td>
            <td class="active">Tên bài báo</td>
            <td class="active">Nơi xuất bản</td> 
            <td class="active">Năm xuất bản</td>
            <td class="active">Ghi chú</td>                  
          </tr>
        </thead>
        <tbody>                  
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Tên bài báo">Tên bài báo</td>
            <td data-title="Nơi xuất bản">Nơi xuất bản</td> 
            <td data-title="Năm xuất bản">Năm xuất bản</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
          <tr>
            <td data-title="STT">1</td>
            <td data-title="Tên bài báo">Tên bài báo</td>
            <td data-title="Nơi xuất bản">Nơi xuất bản</td> 
            <td data-title="Năm xuất bản">Năm xuất bản</td>
            <td data-title="Ghi chú">Ghi chú</td>                  
          </tr>
        </tbody>
      </table>
    </div>
  <?php if($can_edit==1){ ?>
    <!-- 
      THÔNG TIN CÁ NHÂN
      Phần 1: Thông tin cá nhân
    -->  
    <div class="modal fade" id="modal-infor-1" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><strong>CẬP NHẬT THÔNG TIN CÁ NHÂN</strong></h4>
          </div>
          <div class="modal-body"> 
            <?php              
              $edit_infor_form=$this->edit_infor_form;
              $edit_infor_form->setAttribute('action', $this->url("application/crud", array('action'=>'edit-infor')));
              $edit_infor_form->setAttribute('class','form');
              $edit_infor_form->setAttribute('role','form');
              $edit_infor_form->setAttribute('method','post');
              $edit_infor_form->prepare();
              echo $this->form()->openTag($edit_infor_form);
            ?>   
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <?php foreach ($all_attributes as $key => $all_attribute) { ?>
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php echo $this->formLabel($edit_infor_form->get($all_attribute['attribute_code'])); ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($edit_infor_form->get($all_attribute['attribute_code'])); ?> 
                  </div>
                </div>
              </div>  
            <?php } ?>          
            <div class="row">                  
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                <button type="submit" class="btn btn-default">Lưu</button>
              </div>
            </div>
            <?php echo $this->form()->closeTag($edit_infor_form); ?>
          </div>            
        </div>
      </div>
    </div>

    <!-- 
      THÔNG TIN CÁ NHÂN
      Phần 2: Các chứng chỉ
     -->  
    <div class="modal fade" id="modal-infor-2" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><strong>CẬP NHẬT THÔNG TIN CÁ NHÂN</strong></h4>
          </div>
          <div class="modal-body"> 
            <?php
              $certificate_edit_form=$this->certificate_edit_form;
              $certificate_edit_form->setAttribute('action', $this->url("application/crud", array('action'=>'edit-certificate')));
              $certificate_edit_form->setAttribute('class','form');
              $certificate_edit_form->setAttribute('role','form');
              $certificate_edit_form->setAttribute('method','post');
              $certificate_edit_form->prepare();
              echo $this->form()->openTag($certificate_edit_form);
            ?>  
            <input type="hidden" name="id" value="<?php echo $this->id; ?>"> 
            <?php
              foreach ($certificate_lists as $key => $certificate_list) {
            ?>
              <?php if($key>0){ ?>
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <hr/>
                </div>              
              </div>
              <?php } ?>
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    // input id
                    $certificate_id='certificate_id_'.$certificate_list['value_id'];
                    echo $this->formHidden($certificate_edit_form->get($certificate_id));
                    // Label name
                    $certificate_name='certificate_name_'.$certificate_list['value_id'];
                    $certificate_edit_form->get($certificate_name)->setLabel('Tên chứng chỉ');
                    echo $this->formLabel($certificate_edit_form->get($certificate_name)); 
                  ?>
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php
                      // input name
                      echo $this->formElement($certificate_edit_form->get($certificate_name));
                    ?>
                  </div>
                </div>
              </div>
              <?php
                if($certificate_list['name']!='Ngoại ngữ'){
              ?>
                <div class="row">
                  <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">                    
                    <?php 
                      // label checkbox
                      $checkbox='certificate_check_'.$certificate_list['value_id']; 
                      $certificate_edit_form->get($checkbox)->setLabel('Có/Không');
                      echo $this->formLabel($certificate_edit_form->get($checkbox));

                    ?>
                  </div>
                  <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                    <div class="form-group has-success">
                      <?php 
                        // input checkbox  
                        echo $this->formElement($certificate_edit_form->get($checkbox));
                      ?>  
                    </div>
                  </div>
                </div> 
                <div class="row">
                  <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                    <?php 
                      // label note
                      $note='certificate_note_'.$certificate_list['value_id']; 
                      $certificate_edit_form->get($note)->setLabel('Ghi chú');
                      echo $this->formLabel($certificate_edit_form->get($note));

                    ?>
                  </div>
                  <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                    <div class="form-group has-success">  
                      <?php
                        //  input note  
                        echo $this->formElement($certificate_edit_form->get($note));
                      ?>
                    </div>
                  </div>
                </div>
              <?php
                }
                else{
              ?>
                  <div class="row">
                    <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                      <?php 
                        // label loại ngoại ngữ
                        $loai_ngoai_ngu='certificate_loai_ngoai_ngu_'.$certificate_list['value_id']; 
                        $certificate_edit_form->get($loai_ngoai_ngu)->setLabel('Loại ngoại ngữ');
                        echo $this->formLabel($certificate_edit_form->get($loai_ngoai_ngu));
                      ?>
                    </div>
                    <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                      <div class="form-group has-success">
                        <?php
                          //  input loại ngoại ngữ  
                          echo $this->formElement($certificate_edit_form->get($loai_ngoai_ngu));
                        ?>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                      <?php 
                        // label loại ngoại ngữ
                        $level='certificate_level_'.$certificate_list['value_id']; 
                        $certificate_edit_form->get($level)->setLabel('Trình độ');
                        echo $this->formLabel($certificate_edit_form->get($level));
                      ?>
                    </div>
                    <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                      <div class="form-group has-success">                  
                        <?php
                          //  input note  
                          echo $this->formElement($certificate_edit_form->get($level));
                        ?>
                      </div>
                    </div>
                  </div>
              <?php } ?>
            <?php 
              }
            ?>          
            <div class="row">                  
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                <button type="submit" class="btn btn-default">Lưu</button>
              </div>
            </div>
            <?php echo $this->form()->closeTag($certificate_edit_form); ?>
          </div>            
        </div>
      </div>
    </div>

    <!-- 
      KINH NGHIỆM LÀM VIỆC
      Phần 1: Công tác giảng dạy
    -->  
      <!-- add -->
      <div class="modal fade" id="modal-cong-tac-giang-day-add" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"><strong>THÊM CÔNG TÁC GIẢNG DẠY</strong></h4>
            </div>
            <div class="modal-body"> 
              <?php
                $teaching_add_form=$this->teaching_add_form;
                $teaching_add_form->setAttribute('action', $this->url("application/crud", array('action'=>'add-teaching')));
                $teaching_add_form->setAttribute('class','form');
                $teaching_add_form->setAttribute('role','form');
                $teaching_add_form->setAttribute('method','post');
                $teaching_add_form->prepare();
                echo $this->form()->openTag($teaching_add_form);
              ?>  
              <input type="hidden" name="id" value="<?php echo $this->id; ?>">
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_add_form->get('ten_mon')->setLabel('Tên môn');
                    echo $this->formLabel($teaching_add_form->get('ten_mon')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_add_form->get('ten_mon')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_add_form->get('so_tiet')->setLabel('Số tiết');
                    echo $this->formLabel($teaching_add_form->get('so_tiet')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_add_form->get('so_tiet')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Bậc học
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($bac_hocs as $key => $bac_hoc) { ?>
                      <label class="btn btn-default" title="<?php echo $bac_hoc; ?>">
                        <?php echo $this->formElement($teaching_add_form->get('bac_hoc_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $bac_hoc; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Hệ đào tạo
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($he_dao_taos as $key => $he_dao_tao) { ?>
                      <label class="btn btn-default" title="<?php echo $he_dao_tao; ?>">
                        <?php echo $this->formElement($teaching_add_form->get('he_dao_tao_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $he_dao_tao; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_add_form->get('ghi_chu')->setLabel('Ghi chú');
                    echo $this->formLabel($teaching_add_form->get('ghi_chu')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_add_form->get('ghi_chu')); ?> 
                  </div>
                </div>
              </div>
                       
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($teaching_add_form); ?>
            </div>            
          </div>
        </div>
      </div>
      <!-- edit -->
      <div class="modal fade" id="modal-cong-tac-giang-day-edit" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"><strong>SỬA CÔNG TÁC GIẢNG DẠY</strong></h4>
            </div>
            <div class="modal-body"> 
              <?php
                $teaching_edit_form=$this->teaching_edit_form;
                $teaching_edit_form->setAttribute('action', $this->url("application/crud", array('action'=>'edit-teaching', 'id'=>$this->id)));
                $teaching_edit_form->setAttribute('class','form');
                $teaching_edit_form->setAttribute('role','form');
                $teaching_edit_form->setAttribute('method','post');
                $teaching_edit_form->prepare();
                echo $this->form()->openTag($teaching_edit_form);
                echo $this->formHidden($teaching_edit_form->get('id_cong_tac'));
              ?>
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_edit_form->get('ten_mon')->setLabel('Tên môn');
                    echo $this->formLabel($teaching_edit_form->get('ten_mon')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_edit_form->get('ten_mon')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_edit_form->get('so_tiet')->setLabel('Số tiết');
                    echo $this->formLabel($teaching_edit_form->get('so_tiet')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_edit_form->get('so_tiet')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Bậc học
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($bac_hocs as $key => $bac_hoc) { ?>
                      <label class="btn btn-default" title="<?php echo $bac_hoc; ?>">
                        <?php echo $this->formElement($teaching_edit_form->get('bac_hoc_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $bac_hoc; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Hệ đào tạo
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($he_dao_taos as $key => $he_dao_tao) { ?>
                      <label class="btn btn-default" title="<?php echo $he_dao_tao; ?>">
                        <?php echo $this->formElement($teaching_edit_form->get('he_dao_tao_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $he_dao_tao; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $teaching_edit_form->get('ghi_chu')->setLabel('Ghi chú');
                    echo $this->formLabel($teaching_edit_form->get('ghi_chu')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($teaching_edit_form->get('ghi_chu')); ?> 
                  </div>
                </div>
              </div>
                       
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($teaching_edit_form); ?>
            </div>            
          </div>
        </div>
      </div>







      <!-- 
      ĐỊNH HƯỚNG PHÁT TRIỂN
      Phần 1: Công tác giảng dạy
    -->  
      <!-- add -->
      <div class="modal fade" id="modal-future-cong-tac-giang-day-add" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"><strong>THÊM CÔNG TÁC GIẢNG DẠY TRONG TƯƠNG LAI</strong></h4>
            </div>
            <div class="modal-body"> 
              <?php
                $future_teaching_add_form=$this->future_teaching_add_form;
                $future_teaching_add_form->setAttribute('action', $this->url("application/crud", array('action'=>'add-future-teaching')));
                $future_teaching_add_form->setAttribute('class','form');
                $future_teaching_add_form->setAttribute('role','form');
                $future_teaching_add_form->setAttribute('method','post');
                $future_teaching_add_form->prepare();
                echo $this->form()->openTag($future_teaching_add_form);
              ?>  
              <input type="hidden" name="id" value="<?php echo $this->id; ?>">
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_add_form->get('ten_mon')->setLabel('Tên môn');
                    echo $this->formLabel($future_teaching_add_form->get('ten_mon')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_add_form->get('ten_mon')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_add_form->get('so_tiet')->setLabel('Số tiết');
                    echo $this->formLabel($future_teaching_add_form->get('so_tiet')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_add_form->get('so_tiet')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Bậc học
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($bac_hocs as $key => $bac_hoc) { ?>
                      <label class="btn btn-default" title="<?php echo $bac_hoc; ?>">
                        <?php echo $this->formElement($future_teaching_add_form->get('bac_hoc_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $bac_hoc; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Hệ đào tạo
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($he_dao_taos as $key => $he_dao_tao) { ?>
                      <label class="btn btn-default" title="<?php echo $he_dao_tao; ?>">
                        <?php echo $this->formElement($future_teaching_add_form->get('he_dao_tao_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $he_dao_tao; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_add_form->get('ghi_chu')->setLabel('Ghi chú');
                    echo $this->formLabel($future_teaching_add_form->get('ghi_chu')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_add_form->get('ghi_chu')); ?> 
                  </div>
                </div>
              </div>
                       
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($future_teaching_add_form); ?>
            </div>            
          </div>
        </div>
      </div>
      <!-- edit -->
      <div class="modal fade" id="modal-future-cong-tac-giang-day-edit" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"><strong>SỬA CÔNG TÁC GIẢNG DẠY TRONG TƯƠNG LAI</strong></h4>
            </div>
            <div class="modal-body"> 
              <?php
                $future_teaching_edit_form=$this->future_teaching_edit_form;
                $future_teaching_edit_form->setAttribute('action', $this->url("application/crud", array('action'=>'edit-future-teaching', 'id'=>$this->id)));
                $future_teaching_edit_form->setAttribute('class','form');
                $future_teaching_edit_form->setAttribute('role','form');
                $future_teaching_edit_form->setAttribute('method','post');
                $future_teaching_edit_form->prepare();
                echo $this->form()->openTag($future_teaching_edit_form);
                echo $this->formHidden($future_teaching_edit_form->get('id_cong_tac'));
              ?>
              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_edit_form->get('ten_mon')->setLabel('Tên môn');
                    echo $this->formLabel($future_teaching_edit_form->get('ten_mon')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_edit_form->get('ten_mon')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_edit_form->get('so_tiet')->setLabel('Số tiết');
                    echo $this->formLabel($future_teaching_edit_form->get('so_tiet')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_edit_form->get('so_tiet')); ?> 
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Bậc học
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($bac_hocs as $key => $bac_hoc) { ?>
                      <label class="btn btn-default" title="<?php echo $bac_hoc; ?>">
                        <?php echo $this->formElement($future_teaching_edit_form->get('bac_hoc_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $bac_hoc; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  Hệ đào tạo
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">                  
                    <div class="btn-group" data-toggle="buttons">
                      <?php foreach ($he_dao_taos as $key => $he_dao_tao) { ?>
                      <label class="btn btn-default" title="<?php echo $he_dao_tao; ?>">
                        <?php echo $this->formElement($future_teaching_edit_form->get('he_dao_tao_'.$key)); ?>
                        <span class="hidden-xs"><?php echo $he_dao_tao; ?></span><span class="hidden-sm hidden-md hidden-lg"><?php echo $key; ?></span>
                      </label>
                      <?php } ?>
                      
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-3 col-md-3 col-lg-2">
                  <?php 
                    $future_teaching_edit_form->get('ghi_chu')->setLabel('Ghi chú');
                    echo $this->formLabel($future_teaching_edit_form->get('ghi_chu')); 
                  ?> 
                </div>
                <div class="col-xs-8 col-sm-9 col-md-9 col-lg-10">
                  <div class="form-group has-success">
                    <?php echo $this->formElement($future_teaching_edit_form->get('ghi_chu')); ?> 
                  </div>
                </div>
              </div>
                       
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($future_teaching_edit_form); ?>
            </div>            
          </div>
        </div>
      </div>
  <?php } ?>   
<?php } ?>
