      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">          
          <h3>Thông tin ngoại ngữ</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-8 col-sm-9 col-md-10 col-lg-10">
          <div class="form-group has-success">
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right">
          <button class="btn btn-default">Thêm</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead>
                <tr class="cf">
                  <th class="active">STT</th>
                  <th class="active">Tên ngoại ngữ</th>
                  <th class="active text-center td-kich-hoat">Kích hoạt</th>                  
                </tr>
              </thead>
              <tbody>                  
                <tr>
                  <td data-title="STT">1</td>
                  <td data-title="Tên ngoại ngữ">Tiếng anh</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">2</td>
                  <td data-title="Tên ngoại ngữ">Tiếng nhật</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">3</td>
                  <td data-title="Tên ngoại ngữ">Tiếng pháp</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">4</td>
                  <td data-title="Tên ngoại ngữ">Tiếng Trung</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Bật</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>