<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php 
            echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) 
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            //->prependStylesheet($this->basePath() . '/css/zf2-style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            //->prependStylesheet($this->basePath() . '/css/flat-ui/flat-ui.css')
            ->prependStylesheet($this->basePath() . '/css/datetime-picker/bootstrap-datetimepicker.css')
            ->prependStylesheet($this->basePath() . '/css/custom/custom.css');
        ?>

        <!-- Scripts -->
        <?php 
            echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
            //->prependFile($this->basePath() . '/js/flat-ui/flat-ui.min.js')            
            ->prependFile($this->basePath() . '/js/sticky/jquery.sticky.js')
            ->prependFile($this->basePath() . '/js/datetime-picker/bootstrap-datetimepicker.js')
            ->prependFile($this->basePath() . '/js/function/function.js')
            ->prependFile($this->basePath() . '/js/custom/custom.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
    <?php
      use Zend\Authentication\AuthenticationService;
      $layout=$this->layout();
      $login_form=$layout['login_form'];
      $danh_sach_giang_viens=$layout['danh_sach_giang_viens'];      
      $id_giang_vien_mac_dinh='';
      if(isset($layout['id_giang_vien_mac_dinh'])){
        $id_giang_vien_mac_dinh=$layout['id_giang_vien_mac_dinh'];
      }

      // tạo url
      $route_name=$layout['route_name'];
      $route_array=$layout['route_array'];
      $url=$this->url($route_name, $route_array);
      if(isset($layout['url'])){
        $url=$layout['url'];
      }

      $user_id='';
      if(isset($layout['user_id'])){
        $user_id=$layout['user_id'];
      }
    ?>    
    <div id="header">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">            
            <a class="navbar-brand" href="<?php echo $this->url('application/crud', array('action'=>'index')); ?>"><span class="hidden-md hidden-lg">ĐHTV</span><span class="hidden-xs hidden-sm">Trường Đại học Trà Vinh</span></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav hidden-sm">               
              <!--<li class="active"><a href="#">Xin chào: Nguyễn Hoàng Duy Thiện!</a></li>
              <li><a href="#">Link</a></li> 
              -->
            </ul>
            <!-- 
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form> 
            -->
           
            
            <ul class="nav navbar-nav navbar-right">              
              <?php    
                // sử dụng partial
                $this->navigation()->menu()->setPartial('application/partial/menu');
                echo $this->navigation('Navigation')->menu()->render();          
                $auth = new AuthenticationService();
                $read = $auth->getStorage()->read(); 
                if($auth->hasIdentity() and isset($read['username'])){
              ?>
                  <li><a href="<?php echo $this->url('permission/user',array('action'=>'logout')); ?>"><b class="glyphicon glyphicon-off"></b> Thoát</a></li>
              <?php
                }
                else{
              ?>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Đăng nhập</a>
                    <ul class="dropdown-menu form-login">
                      <li>
                        <div class="row">
                          <div class="col-xs-12">
                            <?php
                              $login_form->setAttribute('action', $this->url("permission/user", array('action'=>'login')));
                              $login_form->setAttribute('class','form');
                              $login_form->setAttribute('role','form');
                              $login_form->setAttribute('id','login-nav');
                              $login_form->setAttribute('accept-charset','UTF-8');
                              $login_form->setAttribute('method','post');
                              $login_form->prepare();
                              echo $this->form()->openTag($login_form);
                            ?>                        
                              <div class="form-group">
                                <label class="sr-only" for="exampleInputEmail2">Tên đăng nhập</label>
                                <?php
                                  $login_form->get('url')->setAttribute('value', $url);
                                  echo $this->formInput($login_form->get('url'));
                                  echo $this->formInput($login_form->get('username'));
                                ?>
                              </div>
                              <div class="form-group">
                                <label class="sr-only" for="exampleInputPassword2">Mật khẩu</label>                            
                                <?php
                                  echo $this->formInput($login_form->get('password'));
                                ?>
                              </div>                          
                              <div class="form-group">                            
                                <?php                              
                                  echo $this->formRow($login_form->get('submit'));
                                ?>
                              </div>                        
                            <?php echo $this->form()->closeTag($login_form); ?>
                          </div>
                        </div>
                      </li>                  
                    </ul>
                  </li>
              <?php
                }
              ?>
            </ul>            
          </div>
        </div>
      </nav>    

    </div><!-- header -->
    <div id="content">
      <div class="row">        
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 ">
          <div class="danh-sach-giang-vien">
            <div class="panel panel-default table-responsive">
              <div class="panel-heading">
                <h3 class="panel-title">Danh sách giảng viên</h3>
                <div class="pull-right pull-right-btn-filter">
                  <span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
                    <i class="glyphicon glyphicon-filter"></i>
                  </span>
                </div>
              </div>
              <div class="panel-body">
                <input type="text" class="form-control" id="task-table-filter" data-action="filter" data-filters="#task-table" placeholder="Tìm kiếm giảng viên" />
              </div>
              <table class="table table-bordered table-hover pointer" id="task-table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Họ và tên</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                    foreach ($danh_sach_giang_viens as $key => $danh_sach_giang_vien) { 
                      $key++;
                      ?>
                      <tr onclick="setLocation('<?php echo $this->url("application/crud", array("action"=>"index", "id"=>$danh_sach_giang_vien["id"])); ?>')" <?php echo ($danh_sach_giang_vien["id"]==$id_giang_vien_mac_dinh) ? 'class="active"':''; ?>>
                        <td><?php echo $key; ?></td>
                        <td>
                          <?php echo $danh_sach_giang_vien['name']; ?> 
                          <?php if($user_id and $user_id==$danh_sach_giang_vien['id']){ ?>
                            <b class="glyphicon glyphicon-star-empty"></b>
                          <?php } ?>
                        </td>
                      </tr>
                      <?php
                    }
                  ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
          <!-- báo cáo xử lý bằng jQuery -->
          <div id="alert" class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <span>Đăng nhập thành công</span>
          </div>
          <?php
            // báo cáo xử lý băng zend
            $flash=$this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
             <button type="button" id="btn-flash-messenger" class="close" data-dismiss="alert" aria-hidden="true">
                 &times;
             </button>
             <ul><li>')
             ->setMessageSeparatorString('</li><li>')
             ->setMessageCloseString('</li></ul></div>');
             $error=$flash->render('error', array('alert', 'alert-dismissable','alert-danger'));
             echo $error;
             $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
             echo $info;
             $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
             echo $default;
             $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
             echo $success;                     
            if($error||$success||$info||$default)
            { 
              echo "
                <script type='text/javascript'>
                  jQuery('.alert').slideDown('slow').delay(1000).slideUp('slow');
                </script>";                       
            }
          ?> 
          <?php echo $this->content; ?>
        </div>       
      </div>  
    </div><!-- content -->
    <div id="footer">
      
    </div><!-- footer -->
    </body>
</html>
