<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CongTacNghienCuu\Module'                        => __DIR__ . '/Module.php',
    'CongTacNghienCuu\Controller\CongTacNghienCuuController' => __DIR__ . '/src/CongTacNghienCuu/Controller/CongTacNghienCuuController.php',
    'CongTacNghienCuuTest\Framework\TestCase'        => __DIR__ . '/tests/CongTacNghienCuu/Framework/TestCase.php',
    'CongTacNghienCuuTest\SampleTest'                => __DIR__ . '/tests/CongTacNghienCuu/SampleTest.php',
);
