    <div class="row">
        <div class="col-xs-12 hidden-sm hidden-md hidden-lg">&nbsp;</div>
        <div class="col-xs-12 col-sm-10 col-md-10 col-lg-8 col-sm-offset-1 col-md-offset-1 col-lg-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3>Đăng nhập</h3><br>         
              <div class="form-group has-success">
                <input type="text" class="form-control" placeholder="Tên đăng nhập">
              </div>
              <div class="form-group has-success">
                <input type="password" class="form-control" placeholder="Mật khẩu">
              </div>
              <div class="form-group has-success">
                <a href="index.html" class="btn btn-default active">Hủy</a>&nbsp;<button class="btn btn-default">Đăng nhập</button>
              </div>
            </div>            
          </div>
        </div>
    </div>    