<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Route\Module'                        => __DIR__ . '/Module.php',
    'Route\Controller\RouteController' => __DIR__ . '/src/Route/Controller/RouteController.php',
    'RouteTest\Framework\TestCase'        => __DIR__ . '/tests/Route/Framework/TestCase.php',
    'RouteTest\SampleTest'                => __DIR__ . '/tests/Route/SampleTest.php',
);
