
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Thông tin năm học</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10">
          <div class="form-group has-success">
            <input type="text" class="form-control date-time">
          </div>
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 text-right">
          <button class="btn btn-default">Thêm</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Năm</th>
                  <th class="active text-center td-kich-hoat">Kích hoạt</th>                  
                </tr>
              </thead>
              <tbody>                  
                <tr>
                  <td>1</td>
                  <td>2015</td>
                  <td class="text-center">
                    <button class="btn btn-default"><span class="glyphicon glyphicon-ok text-success"></span> Hoạt động</button>
                  </td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>2014</td>
                  <td class="text-center">
                    <button class="btn btn-default">&nbsp;&nbsp;&nbsp;Kích hoạt&nbsp;&nbsp;&nbsp;</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>