      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Thông tin môn học</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10">
          <div class="form-group has-success">
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 text-right">
          <button class="btn btn-default">Thêm</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead class="cf">
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Tên môn</th>
                  <th class="active text-center td-kich-hoat">Kích hoạt</th>                  
                </tr>
              </thead>
              <tbody>                  
                <tr>
                  <td data-title="STT">1</td>
                  <td data-title="Tên môn">Lý thuyết đồ thị</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">2</td>
                  <td data-title="Tên môn">Khai khoáng dữ liệu</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">3</td>
                  <td data-title="Tên môn">Lập trình hệ thống</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Tắt</button>
                  </td>
                </tr>
                <tr>
                  <td data-title="STT">4</td>
                  <td data-title="Tên môn">Lập trình .Net</td>
                  <td class="text-center" data-title="Kích hoạt">
                    <button class="btn btn-default">Bật</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>