    <?php 
      $add_form=$this->add_form;
      $add_form->setAttribute('action', $this->url("mon_hoc/crud", array('action'=>'add')));
      $add_form->setAttribute('class','form');
      $add_form->setAttribute('role','form');
      $add_form->setAttribute('method','post');
      $add_form->prepare();
      echo $this->form()->openTag($add_form);

      $all_subjects=$this->all_subjects; 
    ?>  
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Thông tin môn học</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10">
          <div class="form-group has-success">
            <?php echo $this->formInput($add_form->get('name')); ?>
          </div>
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 text-right">
          <button class="btn btn-default">Thêm</button>
        </div>
      </div>
    <?php  echo $this->form()->closeTag($add_form); ?>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead class="cf">
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Tên môn</th>
                  <th class="active text-center td-kich-hoat">Xóa</th>
                  <th class="active text-center td-kich-hoat">Sửa</th>
                </tr>
              </thead>
              <tbody>   
                <?php foreach ($all_subjects as $key => $all_subject) { ?>               
                <tr>
                  <td data-title="STT"><?php $key++; echo $key; ?></td>
                  <td data-title="Tên môn"><?php echo $all_subject['name']; ?></td>
                  <td class="text-center" data-title="Sửa">
                    <a class="btn btn-default" onclick="deleteConfirm('Bạn mốn xóa môn học này?', '<?php echo $this->url('mon_hoc/crud', array('action'=>'delete', 'id'=>$all_subject['value_id'])); ?>')">Xóa</a>
                  </td>
                  <td class="text-center" data-title="Sửa">
                    <a class="btn btn-default modal-mon-hoc" data-mon-hoc="<?php echo $all_subject['name'] ?>" id-mon-hoc="<?php echo $all_subject['value_id']; ?>">Sửa</a>
                  </td>
                </tr>
                <?php } ?>                
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="modal fade" id="modal-mon-hoc" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Cập nhật môn học</h4>
            </div>
            <div class="modal-body"> 
              <?php
                $edit_form=$this->edit_form;
                $edit_form->setAttribute('action', $this->url("mon_hoc/crud", array('action'=>'edit')));
                $edit_form->setAttribute('class','form');
                $edit_form->setAttribute('role','form');
                $edit_form->setAttribute('method','post');
                $edit_form->prepare();
                echo $this->form()->openTag($edit_form);
              ?>            
              <div class="row">                  
                <div class="col-xs-8 col-sm-9 col-md-10 col-lg-10">
                  
                  <div class="form-group has-success">
                    <?php echo $this->formHidden($edit_form->get('value_id')); ?>
                    <?php echo $this->formInput($edit_form->get('name')); ?>                  
                    
                  </div>
                </div>
                <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($edit_form); ?>
            </div>            
          </div>
        </div>
      </div>