      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Cập nhật danh sách quyền</h3>
        </div>
      </div>      
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead class="cf">
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Tên quyền</th>
                  <th class="active text-center td-kich-hoat">Sửa</th>
                </tr>
              </thead>
              <tbody>  
                <?php
                  $resources=$this->resources;
                  foreach ($resources as $key => $resource) {
                    $key++;
                ?>
                    <tr>
                      <td class="text-center" data-title="STT"><?php echo $key; ?></td>
                      <td data-title="Quyền"><?php echo $resource['resource_name']; ?></td>
                      <td data-title="Kích hoạt" class="text-center">
                        <a class="btn btn-default modal-cap-nhat-quyen" permission-id="<?php echo $resource['resource_id']; ?>" permission-data="<?php echo $resource['resource_name']; ?>">Sửa</a>
                      </td>
                    </tr>
                <?php
                  }
                ?>
                
                
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="modal fade" id="modal-cap-nhat-quyen" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Cập nhật thông tin quyền</h4>
            </div>
            <div class="modal-body"> 
              <?php
                $form = $this->edit_resource_form;
                $form->setAttribute('action', $this->url("permission/permission", array('action' => 'edit')));
                $form->prepare();
                echo $this->form()->openTag($form);
              ?>             
              <div class="row">                  
                <div class="col-xs-8 col-sm-9 col-md-10 col-lg-10">
                  
                  <div class="form-group has-success">
                    <?php echo $this->formHidden($form->get('resource_id')); ?>
                    <?php echo $this->formInput($form->get('resource_name')); ?>                  
                    
                  </div>
                </div>
                <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($form); ?>
            </div>            
          </div>
        </div>
      </div>