    
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Phân quyền</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10">
          <div class="form-group has-success">
            <select class="form-control">
              <option value="">Chọn</option>
              <option value="1">Phạm Tiết Khánh</option>
              <option value="2">Nguyễn Hoàng Duy Thiện</option>
              <option value="3">Lữ Minh Liềng</option>
              <option value="4">Phan Văn Thanh</option>
              <option value="5">Lưu Kim Loan</option>
            </select>
          </div>
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 text-right">
          <button class="btn btn-default">Lưu</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead class="cf">
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Tên quyền</th>
                  <th class="active text-center td-kich-hoat">Kích hoạt</th>                  
                </tr>
              </thead>
              <tbody>                  
                <tr>
                  <td class="text-center" data-title="STT">1</td>
                  <td data-title="Quyền">Sửa thông tin cá nhân</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">2</td>
                  <td data-title="Quyền">Sửa thông tin cá nhân của tất cả các thành viên</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">3</td>
                  <td data-title="Quyền">Quản lý môn học</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">4</td>
                  <td data-title="Quyền">Quản lý năm học</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">5</td>
                  <td data-title="Quyền">Quản lý ngoại ngữ</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">6</td>
                  <td data-title="Quyền">Quản lý nghiên cứu khoa học</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
                <tr>
                  <td class="text-center" data-title="STT">7</td>
                  <td data-title="Quyền">Quản lý phân quyền</td>
                  <td data-title="Kích hoạt">                    
                    <input type="checkbox" class="checkbox">                  
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  