    <?php 
      $add_form=$this->add_form;
      $add_form->setAttribute('action', $this->url("thuoc_tinh/crud", array('action'=>'add')));
      $add_form->setAttribute('class','form');
      $add_form->setAttribute('role','form');
      $add_form->setAttribute('method','post');
      $add_form->prepare();
      echo $this->form()->openTag($add_form);

      $all_attributes=$this->all_attributes; 
    ?>  
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <h3>Thông tin thuộc tính</h3>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="form-group has-success">
            <?php echo $this->formInput($add_form->get('attribute_code')); ?>
          </div>
        </div>
      </div>      
      <div class="row">        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="form-group has-success">
            <?php echo $this->formInput($add_form->get('frontend_label')); ?>
          </div>
        </div>
      </div>
      <div class="row">        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="form-group has-success">
            <?php echo $this->formSelect($add_form->get('frontend_input')); ?>
          </div>
        </div>
      </div>

      <div class="row hidden-xs hidden-sm hidden-md hidden-lg">        
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5 col-xs-offset-2 col-sm-offset-2 col-md-offset-1 col-lg-offset-1">
          <div class="form-group has-success">
            <input type="text" class="form-control" placeholder="Nhập giá trị">
          </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5 col-xs-offset-2 col-sm-offset-2 col-md-offset-0 col-lg-offset-0">
          <div class="form-group has-success">
            <input type="text" class="form-control" placeholder="Nhập tên hiển thị">
          </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-1 col-lg-1 col-xs-offset-2 col-sm-offset-2 col-md-offset-0 col-lg-offset-0">
          <div class="form-group has-success text-right">
            <button class="btn btn-default">+</button>
          </div>
        </div>
      </div>

      <div class="row">        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
          <div class="form-group has-success">
            <button class="btn btn-default">Thêm</button>
          </div>
        </div>
      </div>
      
    <?php  echo $this->form()->closeTag($add_form); ?>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="table-responsive" id="no-more-tables">
            <table class="table table-bordered table-hover cf">
              <thead class="cf">
                <tr>
                  <th class="active">STT</th>
                  <th class="active">Mã thuộc tính</th>
                  <th class="active">Tên thuộc tính</th>
                  <th class="active text-center td-kich-hoat">Xóa</th>
                  <th class="active text-center td-kich-hoat">Sửa</th>
                </tr>
              </thead>
              <tbody>   
                <?php foreach ($all_attributes as $key => $all_attribute) { ?>               
                <tr>
                  <td data-title="STT"><?php $key++; echo $key; ?></td>
                  <td data-title="Mã thuộc tính"><?php echo $all_attribute['attribute_code']; ?></td>
                  <td data-title="Tên thuộc tính"><?php echo $all_attribute['frontend_label']; ?></td>
                  <td class="text-center" data-title="Sửa">
                    <a class="btn btn-default" onclick="deleteConfirm('Bạn mốn xóa thuộc tính này?', '<?php echo $this->url('thuoc_tinh/crud', array('action'=>'delete', 'id'=>$all_attribute['attribute_id'])); ?>')">Xóa</a>
                  </td>
                  <td class="text-center" data-title="Sửa">
                    <a class="btn btn-default modal-attribute" data-attribute-code="<?php echo $all_attribute['attribute_code'] ?>" id-attribute="<?php echo $all_attribute['attribute_id']; ?>" data-frontend-label="<?php echo $all_attribute['frontend_label']; ?>">Sửa</a>
                  </td>
                </tr>
                <?php } ?>                
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="modal fade" id="modal-attribute" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Cập nhật thuộc tính</h4>
            </div>
            <div class="modal-body"> 
              <?php
                $edit_form=$this->edit_form;
                $edit_form->setAttribute('action', $this->url("thuoc_tinh/crud", array('action'=>'edit')));
                $edit_form->setAttribute('class','form');
                $edit_form->setAttribute('role','form');
                $edit_form->setAttribute('method','post');
                $edit_form->prepare();
                echo $this->form()->openTag($edit_form);
              ?>            
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  
                  <div class="form-group has-success">
                    <?php echo $this->formHidden($edit_form->get('attribute_id')); ?>
                    <?php echo $this->formInput($edit_form->get('attribute_code')); ?>                  
                    
                  </div>
                </div>                
              </div>
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  
                  <div class="form-group has-success">
                    <?php echo $this->formInput($edit_form->get('frontend_label')); ?>
                  </div>
                </div>
              </div>
              <div class="row">                  
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                  <button type="submit" class="btn btn-default">Lưu</button>
                </div>
              </div>
              <?php echo $this->form()->closeTag($edit_form); ?>
            </div>            
          </div>
        </div>
      </div>