<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'NamHoc\Module'                        => __DIR__ . '/Module.php',
    'NamHoc\Controller\NamHocController' => __DIR__ . '/src/NamHoc/Controller/NamHocController.php',
    'NamHocTest\Framework\TestCase'        => __DIR__ . '/tests/NamHoc/Framework/TestCase.php',
    'NamHocTest\SampleTest'                => __DIR__ . '/tests/NamHoc/SampleTest.php',
);
