<?php 
  public function editCongTacNghienCuuKhoaHoc(){
      // điểm truy cập csdl
      $jos_users_table=$this->getServiceLocator()->get('Permission\Model\JosUsersTable');
      $jos_year_table=$this->getServiceLocator()->get('NamHoc\Model\JosYearTable');
      $id_giang_vien=$this->params('id');
      $read=$this->getServiceLocator()->get('AuthService')->getStorage()->read();
      if(isset($read['username']) and $read['username']){
        // kiểm tra user đang đăng nhập
        $user=$jos_users_table->getGiangVienByArrayConditionAndArrayColumns(array('username'=>$read['username']));
        // kiểm tra user có quyền editAllProfile không
        $white_lists=$read['white_list'];
        $edit_all_profile=0;
        foreach ($white_lists as $key => $white_list) {
          if($white_list['action']=='editAllProfile'){
            $edit_all_profile=1;
          }
        }
        if($user and isset($user[0]['id']) and $id_giang_vien==$user[0]['id']){   
          // nếu đã đăng nhập            
          $edit_all_profile=1;
        }

        if($edit_all_profile==1){

        }
      }      
    }
  
?>